Models/Entities/IPInfos.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Diagnostics.CodeAnalysis;

namespace IPTestFormASP.Models.Entities
{
    public class IPInfos
    {
        public IPInfos()
        {

        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        public string Name { get; set; }
        public string Number { get; set; }
        public string SchoolClass { get; set; }
        public DateTime TurnedInDateTime { get; set; }
        
        public string IPDec { get; set; }
        public string IPBin { get; set; }
        public char NetworkClass { get; set; }
        public string SMBin { get; set; }
        public string SMDec { get; set; }
        public string NABin { get; set; }
        public string NADec { get; set; }
        public string BRABin { get; set; }
        public string BRADec { get; set; }
        public string Range { get; set; }

        public int SubnetCount { get; set; }

        public string SubnetSMBin { get; set; }
        public string SubnetSMDec { get; set; }

        public string SubnetNABin1 { get; set; }
        public string SubnetNADec1 { get; set; }
        public string SubnetBRABin1 { get; set; }
        public string SubnetBRADec1 { get; set; }
        public string SubnetRange1 { get; set; }

        public string SubnetNABin2 { get; set; }
        public string SubnetNADec2 { get; set; }
        public string SubnetBRABin2 { get; set; }
        public string SubnetBRADec2 { get; set; }
        public string SubnetRange2 { get; set; }

        public string SubnetNABin3 { get; set; }
        public string SubnetNADec3 { get; set; }
        public string SubnetBRABin3 { get; set; }
        public string SubnetBRADec3 { get; set; }
        public string SubnetRange3 { get; set; }

        public string InputIPBin { get; set; }
        public char InputNetworkClass { get; set; }
        public string InputSMBin { get; set; }
        public string InputSMDec { get; set; }
        public string InputNABin { get; set; }
        public string InputNADec { get; set; }
        public string InputBRABin { get; set; }
        public string InputBRADec { get; set; }
        public string InputRange { get; set; }
    
        public string InputSubnetSMBin { get; set; }
        public string InputSubnetSMDec { get; set; }

        public string InputSubnetNABin1 { get; set; }
        public string InputSubnetNADec1 { get; set; }
        public string InputSubnetBRABin1 { get; set; }
        public string InputSubnetBRADec1 { get; set; }
        public string InputSubnetRange1 { get; set; }

        public string InputSubnetNABin2 { get; set; }
        public string InputSubnetNADec2 { get; set; }
        public string InputSubnetBRABin2 { get; set; }
        public string InputSubnetBRADec2 { get; set; }
        public string InputSubnetRange2 { get; set; }

        public string InputSubnetNABin3 { get; set; }
        public string InputSubnetNADec3 { get; set; }
        public string InputSubnetBRABin3 { get; set; }
        public string InputSubnetBRADec3 { get; set; }
        public string InputSubnetRange3 { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace IPTestFormASPTeacherApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using IPTestFormASPTeacherApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace IPTestFormASPTeacherApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InternetProtocolController.cs
using IPTestFormASP.Models.Entities;
using IPTestFormASPTeacherApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace IPTestFormASPTeacherApp.Controllers
{
    public class InternetProtocolController : Controller
    {
        private IPService ipService;

        public InternetProtocolController(IPService ipService)
        {
            this.ipService = ipService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult TestsList()
        {
            List<IPInfos> ipInfosList = ipService.GetAllTests();
            return View(ipInfosList);
        }

        [HttpPost]
        public IActionResult Test(int testID)
        {
            IPInfos ipInfos = ipService.GetTestByID(testID);
            return View(ipInfos);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/InternetProtocol/TestsList.cshtml
<title>TestList</title>
<style>
    .flex-container {
        flex: 1 1 auto;
        overflow: auto;
    }

    .test-form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .test-box {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        margin: 20px;
        min-height: 100px;
        width: 60%;
        background-color: #fff;
        box-shadow: 0px 0px 10px rgba(0,0,0,0.4);
        border-radius: 15px;
        padding: 20px;
    }

    .test-number {
        font-size: 40px;
        font-weight: bold;
    }

    .info-container {
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }

    .test-label {
        font-size: 20px;
        font-weight: bold;
        text-align: center;
        margin-bottom: 10px;
    }

    .test-info {
        font-size: 20px;
    } 
</style>
<section class="flex-container">
    @foreach(var test in Model)
    {
        <form class="test-form" method="post" asp-action="Test" asp-controller="InternetProtocol">
        <button class="test-box">
            <input type="hidden" name="testID" value="@test.ID">
            <div class="test-number">Тест №@test.ID</div>
            <div class="info-container">
                <div class="test-label">Имена / Номер / Клас</div>
                <div class="test-info">@test.Name / №@test.Number / @test.SchoolClass</div>
            </div>
            <div class="info-container">
                <div class="test-label">Предадено на:</div>
                    <div class="test-info">@test.TurnedInDateTime.ToString("dd.MM.yy HH:mm:ss")</div>
            </div>
        </button>
        </form>
    }   
</section>

Views/Shared/_Layout.cshtml
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }

        .main-logo {
            position: absolute;
            top: 0;
            left: 0;
            max-width: 160px;
            max-height: 182.19px;
        }

        button, input[type="button"], input[type="submit"] {
            /* Resetting padding and margin */
            padding: 0;
            margin: 0;
            /* Resetting border */
            border: none;
            /* Resetting background and color */
            background-color: transparent;
            color: inherit;
            /* Resetting cursor */
            cursor: pointer;
            /* Resetting outline */
            outline: none;
            /* Resetting text decoration */
            text-decoration: none;
            /* Resetting font */
            font: inherit;
        }

    </style>
</head>
<body>
    <img class="main-logo" src="https://spge-bg.com/wp-content/uploads/2017/05/LogoSPGEwebTr.png">
</body>
</html>
@RenderBody()